### ISSUE TITLE
Couldn't build the library

### ISSUE THREAD

**Issue by avinashdudi** [tdebatty/java-string-similarity#10] opened 2016-08-07 03:06 UTC
Have I tried to build the library after downloading on my machine using maven, it failed and there an error in NGram.java distance() about overriding. I am not sure how to resolve this. Let me know how to execute the example you mentioned in read.me. Thank you.

**Comment by jaredsburrows** [comment] 2016-08-08 02:51
@avinashdudi What did you try? Here is how to do it via the command line:
1. git clone https://github.com/tdebatty/java-string-similarity
2. cd java-string-similarity
3. mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
 - Look here(https://github.com/tdebatty/java-string-similarity/blob/master/.travis.yml)
4. mvn test

**Comment by mpkorstanje** [comment] 2016-08-08 18:34
Looks like a duplicate of #11. You may want to check your IDE's settings.

**Comment by tdebatty** [comment] 2016-08-09 08:48
Hi,
Thank you @avinashdudi for your interest, and thank you @jaredsburrows  and @mpkorstanje for your quick answers!
@avinashdudi : as stated, could you provide more info?

**Comment by jaredsburrows** [comment] 2016-08-09 16:25
@tdebatty You can just close this unless there is a stacktrace of evidence of a build failure.

**Closed** 2016-08-09 17:17 UTC

**Comment by avinashdudi** [comment] 2016-08-11 18:52
@tdebatty I didn't know it was Java 5 proj. I will try to build it with jdk5 and let you know. Is there a speciific reason for writing it in 5 or just it was 5 when you developerd?
@jaredsburrows  Thanks, I didnt check on the trail. Sorry for late comments.

**Comment by tdebatty** [comment] 2016-08-13 10:31
Hi,
java 1.5 is actually the default version for maven projects: 
https://maven.apache.org/plugins/maven-compiler-plugin/

In anyway I removed the override annotation from NGram.distance() as it was not required...
Best regards!
